EOnego/Areas/Admin/Controllers/CategoryController.cs
using EOnego.DataAccess.Repository.IRepository;
using EOnego.Models;
using EOnego.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;

namespace EOnego.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =SD.Role_Admin +","+ SD.Role_Employee)]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }
        #region APIs
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _unitOfWork.category.GetAll() });
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var categoryIndb = _unitOfWork.category.Get(id);
            if (categoryIndb == null)
                return Json(new { success = false, message = "something went wrong" });
            _unitOfWork.category.Remove(categoryIndb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "data succesfully delete" });

        }
        #endregion
        
        // upsert code start from here----
        public IActionResult upsert(int? id)
        {
            Category category = new Category();
            //for create
            if (id == null) return View(category);
            //for Edit
            category = _unitOfWork.category.Get(id.GetValueOrDefault());
            if (category == null) return NotFound();
            return View(category);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult upsert(Category category)
        {
            if (category == null) NotFound();
            if (!ModelState.IsValid) return View(category);
            if (category.Id == 0)
                _unitOfWork.category.Add(category);
            else
                _unitOfWork.category.Update(category);
            _unitOfWork.Save();
            return RedirectToAction("index");
        }
    }
}

EOnego/Areas/Admin/Controllers/CompanyController.cs
//using AspNetCore;
using EOnego.DataAccess.Repository.IRepository;
using EOnego.Models;
using EOnego.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol;

namespace EOnego.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =SD.Role_Admin)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        #region APIs
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _unitOfWork.Company.GetAll() });
        }
        //Delete Action
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var companyIndb = _unitOfWork.Company.Get(id);
            if (companyIndb == null)
                return Json(new { success = false, message = "something worng" });
            _unitOfWork.Company.Remove(companyIndb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Data Deleted Successfully" });
        }

        #endregion
        
        //upsert Action
        public IActionResult upsert(int? id)
        {
            Company company = new Company();
            if (id == null) return View(company);
            //Edit
            company = _unitOfWork.Company.Get(id.GetValueOrDefault());
            if (company == null) return NotFound();
            return View(company);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult upsert(Company company)
        {
            if (company == null) return NotFound();
            if (!ModelState.IsValid) return View(company);
            if (company.Id == 0)
                _unitOfWork.Company.Add(company);
            else
                _unitOfWork.Company.Update(company);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }

    }
}

EOnego/Areas/Admin/Controllers/ProductController.cs
using EOnego.DataAccess.Repository.IRepository;
using EOnego.Models;
using EOnego.Models.ViewModels;
using EOnego.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EOnego.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin +","+ SD.Role_Employee)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }
        #region APIs
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _unitOfWork.Product.GetAll() });
        }
        public IActionResult Delete(int id)
        {
            var ProductIndb = _unitOfWork.Product.Get(id);

            if (ProductIndb == null)
                return Json(new { success = false, message = "something went wrong" });
            // delete image from folder
            var w3RootFind = _webHostEnvironment.WebRootPath; // wwwroot path get
            var fImgPath = Path.Combine(w3RootFind, ProductIndb.ImageUrl.Trim('\\')); //imageurl from productindb 

            if (System.IO.File.Exists(fImgPath))
            {
                System.IO.File.Delete(fImgPath);
            }

            //Delete image from database
            _unitOfWork.Product.Remove(ProductIndb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Data Deleted Successfully" });

        }
        #endregion
        public IActionResult upsert(int? id)
        {
            ProductVM productVM = new ProductVM()
            {
                Product = new Product(),
                CategoryList = _unitOfWork.category.GetAll().Select(cl => new SelectListItem()
                {
                    Text = cl.Name,
                    Value = cl.Id.ToString()
                }),

                CoverTypeList = _unitOfWork.coverType.GetAll().Select(ct => new SelectListItem()
                {
                    Text = ct.Name,
                    Value = ct.Id.ToString()
                })
            };
            if (id == null) return View(productVM); //create

            //Edit 
            productVM.Product = _unitOfWork.Product.Get(id.GetValueOrDefault());
            if (productVM.Product == null) return NotFound();
            return View(productVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult upsert(ProductVM productVM)
        {
            if (ModelState.IsValid)
            {
                var webRootPath = _webHostEnvironment.WebRootPath; //Get Web Root Path
                var files = HttpContext.Request.Form.Files; // File Input Control Access

                //Check if User Uploaded a File
                if (files.Count() > 0)
                {
                    var fileName = Guid.NewGuid().ToString(); // Generate Unique File Name
                    var extension = Path.GetExtension(files[0].FileName); //Get File Extension
                    var uploads = Path.Combine(webRootPath, @"Images\Products"); //Define Upload Path

                    //Handling Image for Edit Operation

                    if (productVM.Product.Id != 0)
                    {
                        var imageExists = _unitOfWork.Product.Get(productVM.Product.Id).ImageUrl;
                        productVM.Product.ImageUrl = imageExists;
                    }

                    //Delete Existing Image if New Image is Uploaded
                    if (productVM.Product.ImageUrl != null)
                    {
                        var imagePath = Path.Combine(webRootPath, productVM.Product.ImageUrl.Trim('\\'));
                        if (System.IO.File.Exists(imagePath))
                        {
                            System.IO.File.Delete(imagePath);
                        }
                    }
                    // this is for create file in products folder & Save New Image to Disk
                    using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    //Save Image Path to Database
                    productVM.Product.ImageUrl = @"\Images\Products\" + fileName + extension;
                }
                else
                {
                    if (productVM.Product.Id != 0)
                    {
                        var imageExists = _unitOfWork.Product.Get(productVM.Product.Id).ImageUrl;
                        productVM.Product.ImageUrl = imageExists;
                    }
                }

                if (productVM.Product.Id == 0)
                    _unitOfWork.Product.Add(productVM.Product);
                else
                    _unitOfWork.Product.Update(productVM.Product);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            // if it doesnot valid

            else
            {
                productVM = new ProductVM()
                {
                    Product = new Product(),
                    CategoryList = _unitOfWork.category.GetAll().Select(ct => new SelectListItem()
                    {
                        Text = ct.Name,
                        Value = ct.Id.ToString()
                    }),

                    CoverTypeList = _unitOfWork.coverType.GetAll().Select(cl => new SelectListItem()
                    {
                        Text = cl.Name,
                        Value = cl.Id.ToString()
                    })
                };

                // Edit 
                if (productVM.Product.Id != 0)
                {
                    productVM.Product = _unitOfWork.Product.Get(productVM.Product.Id);
                }
                return View(productVM);
            }

        }
    }
}

EOnego/Areas/Admin/Controllers/UserController.cs
using EOnego.DataAccess.Data;
using EOnego.DataAccess.Repository.IRepository;
using EOnego.Models;
using EOnego.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EOnego.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =SD.Role_Admin)]
    public class UserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ApplicationDbContext _context;
        public UserController(IUnitOfWork unitOfWork, ApplicationDbContext context)
        {
            _unitOfWork = unitOfWork;
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        #region APIs
        [HttpGet]
        public IActionResult GetAll()
        {
            var userList = _context.users.ToList();  // aspNetUser via applicationUser
            var roles = _context.Roles.ToList(); // aspNetRole
            var userRoles = _context.UserRoles.ToList(); // aspNetUserRoles
            foreach (var user in userList)
            {
                var roleId = userRoles.FirstOrDefault(u => u.UserId == user.Id).RoleId; // fetch roleId
                user.Role = roles.FirstOrDefault(r => r.Id == roleId).Name; // fetch roleName
                if (user.CompanyId == null)
                {
                    user.Company = new Company()
                    {
                        Name=""
                    };
                }
                if(user.CompanyId != null)
                {
                    user.Company = new Company()
                    {
                        Name = _unitOfWork.Company.Get(Convert.ToInt32(user.CompanyId)).Name
                    };
                }
            }
            // Remove admin user
            var adminUser = userList.FirstOrDefault(u => u.Role == SD.Role_Admin);
            userList.Remove(adminUser);
            return Json(new { data = userList });
        }

        // for lock and unlock user
        [HttpPost]
        public IActionResult LockUnlock([FromBody]string id)
        {
            bool isLocked = false;
            var userIndb = _context.users.FirstOrDefault(au => au.Id == id);
            if (userIndb == null)
                return Json(new { success = false, message = "something went wrong while lock and unlock user" });
            if(userIndb !=null && userIndb.LockoutEnd > DateTime.Now)
            {
                userIndb.LockoutEnd = DateTime.Now;
                isLocked = false;
            }
            else
            {
                userIndb.LockoutEnd = DateTime.Now.AddYears(100);
                isLocked = true;
            }
            _context.SaveChanges();
            return Json(new { success = true, message = isLocked == true ? "user successfully locked" : "user successfully unlocked" });
        }
        #endregion
    }
}

EOnego/Views/Shared/_CreateAndBackToListButtons.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-info form-control">Save</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

EOnego/Views/Shared/_EditAndBackToListButtons.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-info form-control">Update</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>

</div>

EOnego/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using EOnego.Utility
@inject IHttpContextAccessor httpContextAccessor
@using Microsoft.AspNetCore.Http
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EOnego</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EOnego.styles.css" asp-append-version="true" />
    @*CSS REF*@
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-info border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EOnego</a>*@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="home" asp-action="index">home</a>
                        </li>
                        @*<li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@

                        @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Management</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">CoverType</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product </a>
                                </div>
                            </li>
                        }

                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Company/User</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">User</a>

                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Order Management</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="AllOrders" asp-action="Index">All Orders</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="DateWiseOrders" asp-action="Index">DateWiseOrder</a>

                                </div>
                            </li>
                        }

                        @*For Session*@
                        @if (httpContextAccessor.HttpContext.Session.GetInt32(SD.Ss_CartSessionCount) != null && httpContextAccessor.HttpContext.Session.GetInt32(SD.Ss_CartSessionCount) != 0)
                        {
                            var count = httpContextAccessor.HttpContext.Session.GetInt32(SD.Ss_CartSessionCount);
                            <li>
                                <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="nav-link text-white"><i class="fas fa-shopping-cart fa-3x"></i>&nbsp;(@count)</a>
                            </li>
                        }
                        else
                        {
                            <li>
                                <a class="nav-link text-white"><i class="fas fa-shopping-cart fa-3x"></i>&nbsp;(0)</a>
                            </li>
                        }

                    </ul>





                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-danger">
            &copy; 2024 - Ecommerce Shopping by Anonymous
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @*JS REF*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @*<script src="https://kit.fontawesome.com/e19c476714.js"></script>*@
    <script src="https://kit.fontawesome.com/84de6e6f6a.js" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EOnego/Views/Shared/_ProductPartialView.cshtml
@model IEnumerable<EOnego.Models.Product>


<div class="row">
    @foreach (var product in Model)
    {
        <div class="col-lg-3 col-md-6">
            <div class="row p-2">
                <div class="col-12  p-1" style="border:1px solid #008cba; border-radius: 5px;">
                    <div class="card" style="border:0px; height:340px; overflow:hidden;">
                        <img src="@product.ImageUrl" class="card-img-top rounded" style="height:200px; object-fit:cover" />
                        <div class="pl-1">
                            <p class="card-title h5"><b style="color:#2c3e50">@product.Title</b></p>
                            <p class="card-title text-primary">by <b>@product.Author</b></p>
                        </div>
                        <div style="padding-left:5px;">
                            <p>List Price: <strike><b class="">₹@product.ListPrice.ToString("0.00")</b></strike></p>
                        </div>
                        <div style="padding-left:5px;">
                            <p style="color:maroon">As low as: <b class="">₹@product.Price100.ToString("0.00")</b></p>
                        </div>
                    </div>
                    <div>
                        <a asp-action="Details" class="btn btn-primary form-control" asp-route-id="@product.Id">Details</a>
                    </div>
                </div>
            </div>
        </div>
    }

</div>